FROM tansoft/openresty-php:latest

RUN \
    #php-fpm debug
    sed -i 's/;error_log = log\/php7\/error.log/error_log = log\/php7\/error.log/' /etc/php7/php-fpm.conf; \
    sed -i 's/;error_log = syslog/error_log = \/var\/log\/applogs\/error_log/' /etc/php7/php.ini;

CMD ["sh","/usr/local/start.sh"]
